sudo: false

cache:
  directories:
    - $HOME/.pip-cache/
    - .tox

addons:
  apt:
    packages:
      - libenchant-dev
      - binutils
      - libproj-dev
      - gdal-bin
      - libgeos-dev

language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

notifications:
  email: false

before_install:
  - wget https://launchpad.net/ubuntu/+archive/primary/+files/libproj-dev_4.9.3-2_i386.deb
  - sudo dpkg -i libproj-dev_4.9.3-2_i386.deb

install:
  - pip install tox-travis
  - pip install coveralls
  - pip install codecov

script:
  - tox

after_script:
  - coveralls
  - codecov
