sudo: false

cache:
  directories:
    - $HOME/.pip-cache/
    - .tox

addons:
  apt:
    packages:
      - libenchant-dev
      - binutils
      - libproj-dev
      - gdal-bin
      - libgeos-dev

language: python

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6

notifications:
  email: false

before_install:
  - wget http://download.osgeo.org/proj/proj-4.9.3.tar.gz;
    tar xf proj-4.9.3.tar.gz;
    pushd proj-4.9.3;
    ./configure --prefix=$HOME/local;
    make;
    sed -i "" -e s/-I// proj.pc;
    make install;
    popd;

install:
  - pip install tox-travis
  - pip install coveralls
  - pip install codecov

script:
  - tox

after_script:
  - coveralls
  - codecov
