version: '3'
services:
  shell:
    build: .
    image: eeweather_shell
    stdin_open: true
    tty: true
    command: /bin/sh
    volumes:
      - .:/app

  docs:
    image: eeweather_shell
    ports:
      - "${HOST_PORT_DOCS:-8000}:8000"
    command: make -C docs livehtml
    volumes:
      - .:/app

  test:
    image: eeweather_shell
    command: py.test -n0
    volumes:
      - .:/app

  jupyter:
    ports:
      - "${HOST_PORT_JUPYTER:-8888}:8888"
    image: eeweather_shell
    command: |
      jupyter notebook --ip=0.0.0.0 --port=8888 --allow-root --no-browser /app/scripts/tutorial.ipynb
    volumes:
      - .:/app
